<?php
/**
 * ZF3 book Vote my Pizza Example Application
 *
 * @author     Ralf Eggert <ralf@travello.de>
 * @link       https://github.com/zf3buch/vote-my-pizza
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 */
?>
<h1><?php echo $this->translate($this->welcome); ?></h1>
<div class="row">
    <div class="col-sm-6">
        <h3>
            <?php echo $this->translate('pizza_heading_best_pizzas') ?>
        </h3>

        <div class="row">
            <?php foreach ($this->topPizzas as $pizza) : ?>
                <?php
                $this->inlineScript()->appendScript(
                    "
    $('#stars-" . $pizza['id'] . "').raty({
        readOnly: true,
        score   : " . round($pizza['rate'], 1) * 5 . ",
        half    : true,
        starOff : '/assets/vendor/raty-2.7.0/images/star-off.png',
        starOn  : '/assets/vendor/raty-2.7.0/images/star-on.png',
        starHalf: '/assets/vendor/raty-2.7.0/images/star-on.png'
    });
    "
                );
                $urlShow = $this->url(
                    'pizza-show', ['id' => $pizza['id']]
                );
                ?>
                <div class="col-md-4">
                    <div class="thumbnail text-center">
                        <a href="<?php echo $urlShow; ?>">
                            <img src="<?php echo $pizza['image'] ?>"
                                 title="<?php echo $pizza['name'] ?>">
                        </a>

                        <div class="caption">
                            <p class="small">
                                <?php echo $pizza['name'] ?>
                            </p>

                            <div class="label label-success">
                                <i class="fa fa-thumbs-up"></i>
                                <?php echo $pizza['pos'] ?>
                            </div>
                            &nbsp;
                            <div class="label label-danger">
                                <i class="fa fa-thumbs-down"></i>
                                <?php echo $pizza['neg'] ?>
                            </div>
                            <div id="stars-<?php echo $pizza['id'] ?>"></div>
                        </div>
                    </div>
                </div>
            <?php endforeach ?>
        </div>
    </div>
    <div class="col-sm-6">
        <h3>
            <?php echo $this->translate('pizza_heading_worst_pizzas') ?>
        </h3>

        <div class="row">
            <?php foreach ($this->flopPizzas as $pizza) : ?>
                <?php
                $this->inlineScript()->appendScript(
                    "
    $('#stars-" . $pizza['id'] . "').raty({
        readOnly: true,
        score   : " . round($pizza['rate'], 1) * 5 . ",
        half    : true,
        starOff : '/assets/vendor/raty-2.7.0/images/star-off.png',
        starOn  : '/assets/vendor/raty-2.7.0/images/star-on.png',
        starHalf: '/assets/vendor/raty-2.7.0/images/star-on.png'
    });
    "
                );
                $urlShow = $this->url(
                    'pizza-show', ['id' => $pizza['id']]
                );
                ?>
                <div class="col-md-4">
                    <div class="thumbnail text-center">
                        <a href="<?php echo $urlShow; ?>">
                            <img src="<?php echo $pizza['image'] ?>"
                                 title="<?php echo $pizza['name'] ?>">
                        </a>

                        <div class="caption">
                            <p class="small">
                                <?php echo $pizza['name'] ?>
                            </p>

                            <div class="label label-success">
                                <i class="fa fa-thumbs-up"></i>
                                <?php echo $pizza['pos'] ?>
                            </div>
                            &nbsp;
                            <div class="label label-danger">
                                <i class="fa fa-thumbs-down"></i>
                                <?php echo $pizza['neg'] ?>
                            </div>
                            <div id="stars-<?php echo $pizza['id'] ?>"></div>
                        </div>
                    </div>
                </div>
            <?php endforeach ?>
        </div>
    </div>
</div>
<div class="well text-center">
    <h2>
        <?php echo $this->translate('pizza_heading_vote_now') ?>
    </h2>
    <p>
        <a href="<?php echo $this->url('pizza-voting') ?>" class="btn btn-success">
            <i class="fa fa-star"></i>
            <?php echo $this->translate('pizza_action_vote'); ?>
        </a>
    </p>
</div>
