<?php
/**
 * ZF3 book Pin Your Pizza Example Application
 *
 * @author     Ralf Eggert <ralf@travello.de>
 * @link       https://github.com/zf3buch/pin-your-pizza
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 */
use Pizza\Form\RestaurantPriceForm;

$urlRestaurant = $this->url(
    'pizza-handle-restaurant',
    ['id' => $this->pizza['id']]
);

/** @var RestaurantPriceForm $form */
$form = $this->restaurantPriceForm;
$form->setAttribute('action', $urlRestaurant);

?>
<h1><?php echo $this->pizza['name']; ?></h1>
<div class="row">
    <?php
    $this->inlineScript()->appendScript(
        "
    $('#stars-" . $this->pizza['id'] . "').raty({
        readOnly: true,
        score   : " . round($this->pizza['rate'], 1) * 5 . ",
        half    : true,
        starOff : '/assets/vendor/raty-2.7.0/images/star-off.png',
        starOn  : '/assets/vendor/raty-2.7.0/images/star-on.png',
        starHalf: '/assets/vendor/raty-2.7.0/images/star-on.png'
    });
    "
    ); ?>
    <div class="col-md-6">
        <div class="thumbnail text-center">
            <img src="<?php echo $this->pizza['image'] ?>"
                 title="<?php echo $this->pizza['name'] ?>">

            <div class="caption">
                <h4><?php echo $this->pizza['name'] ?></h4>

                <div class="label label-success pull-left">
                    <i class="fa fa-thumbs-up"></i>
                    <?php echo $this->pizza['pos'] ?>
                </div>
                <div class="label label-danger pull-right">
                    <i class="fa fa-thumbs-down"></i>
                    <?php echo $this->pizza['neg'] ?>
                </div>
                <div id="stars-<?php echo $this->pizza['id'] ?>"></div>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <?php foreach ($this->pizza['restaurants'] as $restaurant) : ?>
            <div class="panel panel-success">
                <div class="panel-heading">
                    <?php
                    echo sprintf(
                        $this->translate('pizza_message_restaurant'),
                        $restaurant['name']
                    );
                    ?>
                </div>
                <div class="panel-body">
                    <?php
                    echo sprintf(
                        $this->translate('pizza_message_costs'),
                        $this->pizza['name'],
                        $this->currencyFormat(
                            $restaurant['price'],
                            'EUR'
                        ),
                        $this->dateFormat(
                            strtotime($restaurant['date']),
                            IntlDateFormatter::LONG,
                            IntlDateFormatter::MEDIUM
                        )
                    );
                    ?>
                </div>
            </div>
        <?php endforeach ?>
        <?php if ($this->userAllowed('pizza-handle-restaurant')): ?>
        <div class="panel panel-success">
            <div class="panel-heading">
                <?php
                echo sprintf(
                    $this->translate('pizza_heading_new_price'),
                    $this->pizza['name']
                );
                ?>
            </div>
            <div class="panel-body">
                <?php echo $this->form()->openTag($form); ?>
                <div class="form-group">
                    <?php echo $this->formLabel($form->get('name')); ?>
                    <div class="col-sm-8">
                        <?php
                        echo $this->formElement($form->get('name'));
                        echo $this->formElementErrors($form->get('name'));
                        ?>
                    </div>
                </div>
                <div class="form-group">
                    <?php echo $this->formLabel($form->get('price')); ?>
                    <div class="col-sm-8">
                        <?php
                        echo $this->formElement($form->get('price'));
                        echo $this->formElementErrors($form->get('price'));
                        ?>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-4 col-sm-8">
                        <?php
                        echo $this->formElement($form->get('save_price'));
                        ?>
                    </div>
                </div>
            </div>
            <?php echo $this->form()->closeTag(); ?>
        </div>
        <?php endif; ?>
    </div>
</div>
<div class="row">
    <p class="text-center">
        <a href="<?php echo $this->url('pizza-intro') ?>"
           class="btn btn-success">
            <?php echo $this->translate('pizza_action_back_intro'); ?>
        </a>
    </p>
</div>