<?php
/**
 * ZF3 book Vote my Pizza Example Application
 *
 * @author     Ralf Eggert <ralf@travello.de>
 * @link       https://github.com/zf3buch/vote-my-pizza
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 */
?>
<footer id="footer">
    <div class="footer-top"></div>
    <div class="container">
        <div class="row">
            <div class="col-lg-4">
                <h4>ZF3buch Vote My Pizza!</h4>

                <p>
                    Dieses Demoprojekt wurde mit dem
                    <a href="https://github.com/zendframework/zend-expressive-skeleton/"
                       target="_blank">
                        Zend\Expressive Skeleton
                    </a> erstellt und
                    dann angepasst. Das Demoprojekt dient nur als Beispiel,
                    durch die abgegebenen Votings wird sich die Welt
                    <strong>nicht</strong> verändern.
                </p>
            </div>
            <div class="col-lg-4">
                <h4>Zend Framework Links</h4>
                <ul>
                    <li>
                        <a href="http://framework.zend.com/"
                           target="_blank">
                            Zend Framework Website </a>
                    </li>
                    <li>
                        <a href="http://modules.zendframework.com/"
                           target="_blank">
                            Zend Framework 3 Module </a>
                    </li>
                    <li>
                        <a href="https://github.com/zendframework/"
                           target="_blank">
                            Zend Framework Github </a>
                    </li>
                </ul>
            </div>
            <div class="col-lg-4">
                <h4>ZF3buch Links</h4>
                <ul>
                    <li>
                        <a href="http://www.zendframeworkbuch.de/"
                           target="_blank">
                            Website zum ZF3 Buch </a>
                    </li>
                    <li>
                        <a href="https://github.com/zf3buch/vote-my-pizza"
                           target="_blank">
                            GitHub Repository ZF3buch Vote My Pizza!</a>
                    </li>
                    <li>
                        <a href="http://www.ralfeggert.de" target="_blank">
                            Homepage Ralf Eggert </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</footer>
