<?php
/**
 * ZF3 book Vote my Pizza Example Application
 *
 * @author     Ralf Eggert <ralf@travello.de>
 * @link       https://github.com/zf3buch/vote-my-pizza
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 */
?>
<?php $this->headTitle('404 Not Found'); ?>

<h1>Huch!</h1>
<h2>Das ist echt unangenehm.</h2>
<p>Wir sind auf einen "404 Not Found" Fehler gestossen.</p>
<p>
    Du suchst etwas, das hier nicht existiert oder verschoben wurde.
    Du kannst gerne zurück auf die
    <a href="<?php echo $this->url('home', ['lang' => 'de']) ?>">Startseite</a> wechseln.
</p>
