<?php
/**
 * ZF3 book Vote my Pizza Example Application
 *
 * @author     Ralf Eggert <ralf@travello.de>
 * @link       https://github.com/zf3buch/vote-my-pizza
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 */
?>
<?php $this->headTitle(sprintf('%d %s', $this->status, $this->reason)); ?>

<h1>Huch!</h1>
<h2>Das ist echt unangenehm.</h2>
<p>Wir sind auf einen "<?php echo $this->escapeHtml(sprintf('%d %s', $this->status, $this->reason)); ?>" Fehler gestossen.</p>
<?php if ($this->status == 404) : ?>
    <p>
        Du suchst etwas, das hier nicht existiert oder verschoben wurde.
        Du kannst gerne zurück auf die
        <a href="<?php echo $this->url('home', ['lang' => 'de']) ?>">Startseite</a> wechseln.
    </p>
<?php else : ?>
    <pre><code><?php var_dump($this->error); ?></code></pre>
<?php endif; ?>
