<?php
/**
 * ZF3 book Vote my Pizza Example Application
 *
 * @author     Ralf Eggert <ralf@travello.de>
 * @link       https://github.com/zf3buch/vote-my-pizza
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 */
?>
<h1><?= $this->translate($this->welcome); ?></h1>
<div class="well text-center">
  <h3>
    <i class="fa fa-hourglass fa-spin"></i>
    &nbsp; <?= $this->translate('application_message_soon_more'); ?> &nbsp;
    <i class="fa fa-hourglass fa-spin"></i>
  </h3>
</div>
