<?php
/**
 * ZF3 book Pin Your Pizza Example Application
 *
 * @author     Ralf Eggert <ralf@travello.de>
 * @link       https://github.com/zf3buch/pin-your-pizza
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 */
use User\Form\LoginForm;

$urlLogin = $this->url('user-handle-login');

/** @var LoginForm $form */
$form = $this->loginForm;
$form->setAttribute('action', $urlLogin);

?>
<h1><?php echo $this->translate('user_heading_login'); ?></h1>
<div class="row">
    <div class="col-md-6">
        <div class="panel panel-success">
            <div class="panel-heading">
                <?php echo $this->translate('user_heading_login_now'); ?>
            </div>
            <div class="panel-body">
                <?php echo $this->form()->openTag($form); ?>
                <div class="form-group">
                    <?php echo $this->formLabel($form->get('email')); ?>
                    <div class="col-sm-8">
                        <?php
                        echo $this->formElement($form->get('email'));
                        echo $this->formElementErrors($form->get('email'));
                        ?>
                    </div>
                </div>
                <div class="form-group">
                    <?php echo $this->formLabel($form->get('password')); ?>
                    <div class="col-sm-8">
                        <?php
                        echo $this->formElement($form->get('password'));
                        echo $this->formElementErrors($form->get('password'));
                        ?>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-4 col-sm-8">
                        <?php
                        echo $this->formElement($form->get('login_user'));
                        ?>
                    </div>
                </div>
            </div>
            <?php echo $this->form()->closeTag(); ?>
        </div>
    </div>
</div>
<div class="row">
    <p class="text-center">
        <a href="<?php echo $this->url('home') ?>" class="btn btn-success">
            <?php echo $this->translate('application_action_back_home'); ?>
        </a>
    </p>
</div>